# Generated by Django 6.0.3 on 2026-03-31 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCards',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('roommate_score', models.IntegerField(blank=True, max_length=255, null=True)),
                ('housing_score', models.IntegerField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField()),
            ],
            options={
                'db_table': 'Profile',
                'managed': False,
            },
        ),
    ]
