# Generated by Django 6.0.3 on 2026-03-28 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_onboarded', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('non_binary', 'Non-binary'), ('genderqueer', 'Genderqueer / Gender-fluid'), ('agender', 'Agender'), ('self_describe', 'A gender not listed (Self-describe)'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('gender_self_described', models.CharField(blank=True, help_text="If you selected 'A gender not listed', please specify here.", max_length=50, null=True)),
                ('major_minor', models.CharField(blank=True, max_length=120)),
                ('grad_year', models.CharField(blank=True, max_length=50)),
                ('outreach_preference', models.CharField(blank=True, choices=[('phone', 'Phone'), ('instagram', 'Instagram'), ('email', 'Email')], default='email', max_length=20)),
                ('instagram', models.CharField(blank=True, help_text='Handle (e.g. billyrulez) or full URL.', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, help_text='Profile picture (requires Pillow installed).', null=True, upload_to='profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
