# Generated by Django 6.0.3 on 2026-03-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='gender_self_described',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('man', 'Man'), ('woman', 'Woman'), ('non_binary', 'Non-binary'), ('genderqueer', 'Genderqueer / Gender-fluid'), ('agender', 'Agender'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grad_year',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='instagram',
            field=models.CharField(help_text='Handle (e.g. billyrulez) or full URL.', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='major_minor',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='profile',
            name='outreach_preference',
            field=models.CharField(choices=[('phone', 'Phone'), ('instagram', 'Instagram'), ('email', 'Email')], default='email', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(help_text='Profile picture (requires Pillow installed).', null=True, upload_to='profile_photos/'),
        ),
    ]
