# Generated by Django 6.0.3 on 2026-03-29 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_profile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='listing_image',
            field=models.ImageField(blank=True, help_text='Photo of the sublet listing.', null=True, upload_to='listing_photos/'),
        ),
    ]
