# Generated by Django 6.0.3 on 2026-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_profile_listing_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banned',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hidden',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
