# Generated by Django 6.0.3 on 2026-04-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_profile_banned_profile_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_hidden',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
