# Generated by Django 6.0.3 on 2026-04-23 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_user', '0001_initial'),
        ('user_profile', '0007_profile_listing_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('profile', 'Profile'), ('listing', 'Listing')], default='profile', max_length=10)),
                ('reason', models.TextField(blank=True, max_length=300)),
                ('speed', models.CharField(choices=[('asap', 'As fast as possible'), ('fast', 'Fast'), ('normal', 'Normal'), ('less_than_normal', 'Less than normal'), ('no_rush', 'No Rush')], default='normal', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archived', models.BooleanField(default=False, editable=False)),
                ('reported_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to='user_profile.profile')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='UserReport',
        ),
    ]
